### ISSUE TITLE
At service-manager to handle commands / all objects?

### ISSUE THREAD

**Issue by RalfEggert** [zfcampus/zf-console#15]
I thought of adding the ZF2 `ServiceManager` to handle the commands. I think it would make it much easier to create factories to create command instances. Or we could even add all objects to the `ServiceManager`, especially the `Application` instance. That would make it much easier to inject the `Application` instance to the `HelpCommand` as well. We could even refactor the `Application` class and pull out the standard commands to external classes (like the `HelpCommand`). An extra interface could standardize the `__invoke()` methods for all commands. 

Would the effort be worth it or would it introduce an unwanted complexity or overhead?

**Comment by Narno** [comment]
I love the idea! :+1:

**Comment by vaclavvanik** [comment]
Totally agree. Commands without possibility of injecting services into constructor are half-handed.
