### ISSUE TITLE
The best way to remove autocomplete route?

### ISSUE THREAD

**Issue by Narno** [zfcampus/zf-console#17]
Hello,

What is the best way to remove/disable the default "autocomplete" route?

Thank you.

**Comment by RalfEggert** [comment]
Currently, it is only possible to overwrite the standard `autocomplete` route by passing a custom `autocomplete` route to the constructor of `ZF\Console\Application`. The same issue exists for the standard `help` and `version` routes. Furthermore, it is not possible to remove a route from `ZF\Console\RouteCollection` once it was added. 

It would need some refactoring to make it possible to turn of these standard routes.

**Comment by weierophinney** [comment]
Fixed with #18.
