### ISSUE TITLE
Please create new version 1.0.4

### ISSUE THREAD

**Issue by RalfEggert** [zfcampus/zf-console#20]
The last commits merged since 1.0.3 are not tagged with a version number. If I install this via composer I cannot use:

```
"require": {
    "zfcampus/zf-console": "1.*"
},
```

I must use:

```
"require": {
    "zfcampus/zf-console": "dev-master*"
},
```

**Comment by weierophinney** [comment]
@RalfEggert I'll be tagging the last `1.0.*` versions of all zfcampus repos prior to the 1.1 release sometime this week.

**Comment by RalfEggert** [comment]
Nice one. I will close the issue...
