### ISSUE TITLE
Warning generated every time I use console

### ISSUE THREAD

**Issue by GeeH** [zfcampus/zf-console#21]
Hello.

In multiple applications, every time I use a console route I get the following warning:

```
HP Warning:  cli_set_process_title(): cli_set_process_title had an error: Not initialized correctly in /Users/geeh/www/modules.zendframework.com/vendor/zfcampus/zf-console/src/Application.php on line 534
```

This happens both inside and outside of ZF2 app.

Thank you.

**Comment by Narno** [comment]
Hello Gary, I have the same problem on my Mac: It seems this functionality is blocked for security reasons (by Apple).

While waiting to find a better solution, I work around the problem with `@cli_set_proc_title()`.

**Comment by RalfEggert** [comment]
@GeeH can you confirm that your working on a Mac? Which PHP versions are you using?

**Comment by RalfEggert** [comment]
Same problem here with no real solution except using root

https://github.com/liip/php-osx/issues/139

**Comment by GeeH** [comment]
I can indeed - I’m using Mac OS X 10.10.3 and PHP version 5.6.5



On 25 April 2015 at 12:59:46, Ralf Eggert (notifications@github.com) wrote:

Same problem here with no real solution except using root

liip/php-osx#139

**Comment by RalfEggert** [comment]
If you look at the method there is already a version check implemented.

https://github.com/zfcampus/zf-console/blob/master/src/Application.php#L528

Maybe we could add an OS check as well. Would `PHP_OS` be sufficient to identify Mac OS X? What do you get from `var_dump(PHP_OS);`?

Other suggestions to identify OS X?

**Comment by RalfEggert** [comment]
Or maybe `php_uname()` could do the job?

**Comment by GeeH** [comment]
string(6) “Darwin"

HTH :P
On 25 April 2015 at 12:59:46, Ralf Eggert (notifications@github.com) wrote:

Same problem here with no real solution except using root

liip/php-osx#139

**Comment by RalfEggert** [comment]
I will try to provide a fix later on...

**Comment by RalfEggert** [comment]
http://en.wikipedia.org/wiki/Darwin_%28operating_system%29
