### ISSUE TITLE
Wrong zend/console requirement version

### ISSUE THREAD

**Issue by krzysztof-alboszta** [zfcampus/zf-console#23]
as `DefaultRouteMatcher` and `RouteMatcherInterface` was introduced in Zend 2.3.0 release the `composer.json` requirement specified as 

    "zendframework/zend-console": "~2.0"

could not met the proper version of ZendConsole which cause the errors when importing

    use Zend\Console\RouteMatcher\DefaultRouteMatcher;
    use Zend\Console\RouteMatcher\RouteMatcherInterface;

minimal version requirements should be reviewed to prevent that issue

**Comment by RalfEggert** [comment]
Well, since `~2.0` is equivalent to `>=2.0 <3.0` it should be OK, I think. I currently get 2.4.0 installed when updating via Composer.

**Comment by krzysztof-alboszta** [comment]
well but if you have specific version of  Zend Framework installed in version less than 2.3.0 composer would think that everything is OK which is not
so the version should be defined at the minimal requirements

**Comment by RalfEggert** [comment]
Added a fix
